steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t europe-southwest1-docker.pkg.dev/hexitalk/hexitalk-img-registry/chat-ms -f dockerfile.prod --platform=linux/amd64 --build-arg CHAT_MS_PORT=$$CHAT_MS_PORT --build-arg CHAT_DB_URL=$$CHAT_DB_URL --build-arg NATS_PORT=$$NATS_PORT .
    secretEnv: ['CHAT_MS_PORT', 'NATS_PORT', 'CHAT_DB_URL']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-southwest1-docker.pkg.dev/hexitalk/hexitalk-img-registry/chat-ms',
      ]

availableSecrets:
  secretManager:
    - versionName: projects/188352291421/secrets/chat_ms_port/versions/1
      env: 'CHAT_MS_PORT'
    - versionName: projects/188352291421/secrets/nats_port/versions/1
      env: 'NATS_PORT'
    - versionName: projects/188352291421/secrets/chat_db_url/versions/1
      env: 'CHAT_DB_URL'

options:
  logging: CLOUD_LOGGING_ONLY





steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-southwest1-docker.pkg.dev/hexitalk/hexitalk-img-registry/chat-ms',
        '-f',
        'dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-southwest1-docker.pkg.dev/hexitalk/hexitalk-img-registry/chat-ms',
      ]
options:
  logging: CLOUD_LOGGING_ONLY
